### ISSUE TITLE
Contact-us form behaviour

### ISSUE THREAD

**Issue by sumit-narang** [entranceplus/web#17]
- [x] Clicking on the contact-us form shrinks in size. 
- [x] Also the color and fonts need to be changed to white.
- [x] details saved from contact us form should be viewable somewhere

**Comment by sumit-narang** [comment]
@shakdwipeea 2nd point "Also the color....". I think the font color is white. Can you check again?
3rd point "details saved from ....". Do you want to save the contact details to firebase database?

**Comment by shakdwipeea** [comment]
Just checked, colors seem fine. 
I don't know what the problem is in 1.
For third, there should be a unified way to store all the data from the contact us as well as google
form. Something that is easily viewable by @arush365

**Comment by sumit-narang** [comment]
I know the problem in 1[It is happening bcoz of extension grammarly is applied in textarea]. The solution is easy for this.
For third, I will find some simple solution.

**Comment by sumit-narang** [comment]
8.3  details saved from contact us form should be viewable somewhere

contact-us form data is saved in firebase database
