### ISSUE TITLE
Payment pages

### ISSUE THREAD

**Issue by shakdwipeea** [entranceplus/web#20]
I have added initial skeleton. Screens for success and failure is not yet there. @sumit-narang 
dom changes for the same can be done [here](https://github.com/entranceplus/web/blob/master/resources/public/mentorship.html#L54)

**Comment by sumit-narang** [comment]
Error msg:
screen1:
![screen shot 2018-04-16 at 10 14 38 pm](https://user-images.githubusercontent.com/20576051/38823876-37709090-41c5-11e8-82a1-13add08c3c4e.png)
screen2:
![screen shot 2018-04-16 at 10 16 56 pm](https://user-images.githubusercontent.com/20576051/38823899-44dd4cdc-41c5-11e8-9847-a691ee55b758.png)
screen3:
![screen shot 2018-04-16 at 10 17 14 pm](https://user-images.githubusercontent.com/20576051/38823914-4b4ce6a4-41c5-11e8-8fe5-bec31afc1295.png)

Success msg:
screen1:
![screen shot 2018-04-16 at 10 14 38 pm](https://user-images.githubusercontent.com/20576051/38823876-37709090-41c5-11e8-82a1-13add08c3c4e.png)
screen2:
![screen shot 2018-04-16 at 10 21 22 pm](https://user-images.githubusercontent.com/20576051/38823942-61e24c92-41c5-11e8-973c-c121307424cd.png)
screen3:
![screen shot 2018-04-16 at 10 21 55 pm](https://user-images.githubusercontent.com/20576051/38823958-69fa82a0-41c5-11e8-9d6a-151c608facf1.png)
