### ISSUE TITLE
Design fix

### ISSUE THREAD

**Issue by arush365** [entranceplus/web#8]
Rank list, exam list ye tagda lagna chahiye on mobile kyuki crowd yahi se pull hoga

**Comment by arush365** [comment]
Iske alava baaki cheez jo pasha banaya hai ek number hai, if kuch minor fix required hoga kar diya jayega

**Comment by sumit-narang** [comment]
@arush365 @shakdwipeea See this page (https://fir-ep.firebaseapp.com/exam-list.html) in Desktop as of now. This is the design of Ranklist as of now on Desktop.

Any list page [like ranklist or list of anything] is generic. Everywhere on any site [like on any other website], it is the same design.

One thing, we can do it is that give user option to:
1.Print the list
2.View the list in different view for readability.

I am also thinking to improve the Ranklist design.

**Comment by sumit-narang** [comment]
@arush365  @shakdwipeea Feedback to further improve the ranklist page will be appreciated.

**Comment by shakdwipeea** [comment]
Looks nice.
A couple of features that might be important:

Search for college (by name / location)
Sort by (mhrd score / placement score)

**Comment by shakdwipeea** [comment]
Also See #9

**Comment by sumit-narang** [comment]
Change designed of rank-list page
